// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// colmax_cpp
NumericVector colmax_cpp(const NumericMatrix& x);
RcppExport SEXP _forecastdom_colmax_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colmax_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// colmax_selected_cpp
NumericVector colmax_selected_cpp(const NumericMatrix& x, const LogicalVector& selected);
RcppExport SEXP _forecastdom_colmax_selected_cpp(SEXP xSEXP, SEXP selectedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type selected(selectedSEXP);
    rcpp_result_gen = Rcpp::wrap(colmax_selected_cpp(x, selected));
    return rcpp_result_gen;
END_RCPP
}
// divide_colmax_cpp
NumericVector divide_colmax_cpp(const NumericMatrix& tstat, const NumericVector& sigma);
RcppExport SEXP _forecastdom_divide_colmax_cpp(SEXP tstatSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type tstat(tstatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(divide_colmax_cpp(tstat, sigma));
    return rcpp_result_gen;
END_RCPP
}
// divide_colmax_selected_cpp
NumericVector divide_colmax_selected_cpp(const NumericMatrix& tstat, const NumericVector& sigma, const LogicalVector& selected);
RcppExport SEXP _forecastdom_divide_colmax_selected_cpp(SEXP tstatSEXP, SEXP sigmaSEXP, SEXP selectedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type tstat(tstatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type selected(selectedSEXP);
    rcpp_result_gen = Rcpp::wrap(divide_colmax_selected_cpp(tstat, sigma, selected));
    return rcpp_result_gen;
END_RCPP
}
// pvalue_search_cpp
double pvalue_search_cpp(const NumericMatrix& h_hat, const NumericMatrix& sigma_jx_t, const NumericVector& sorted_max, double sqrt_n);
RcppExport SEXP _forecastdom_pvalue_search_cpp(SEXP h_hatSEXP, SEXP sigma_jx_tSEXP, SEXP sorted_maxSEXP, SEXP sqrt_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type h_hat(h_hatSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type sigma_jx_t(sigma_jx_tSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sorted_max(sorted_maxSEXP);
    Rcpp::traits::input_parameter< double >::type sqrt_n(sqrt_nSEXP);
    rcpp_result_gen = Rcpp::wrap(pvalue_search_cpp(h_hat, sigma_jx_t, sorted_max, sqrt_n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_forecastdom_colmax_cpp", (DL_FUNC) &_forecastdom_colmax_cpp, 1},
    {"_forecastdom_colmax_selected_cpp", (DL_FUNC) &_forecastdom_colmax_selected_cpp, 2},
    {"_forecastdom_divide_colmax_cpp", (DL_FUNC) &_forecastdom_divide_colmax_cpp, 2},
    {"_forecastdom_divide_colmax_selected_cpp", (DL_FUNC) &_forecastdom_divide_colmax_selected_cpp, 3},
    {"_forecastdom_pvalue_search_cpp", (DL_FUNC) &_forecastdom_pvalue_search_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_forecastdom(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
