# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colmax_cpp <- function(x) {

    .Call(`_forecastdom_colmax_cpp`, x)

}

colmax_selected_cpp <- function(x, selected) {

    .Call(`_forecastdom_colmax_selected_cpp`, x, selected)

}

divide_colmax_cpp <- function(tstat, sigma) {

    .Call(`_forecastdom_divide_colmax_cpp`, tstat, sigma)

}

divide_colmax_selected_cpp <- function(tstat, sigma, selected) {

    .Call(`_forecastdom_divide_colmax_selected_cpp`, tstat, sigma, selected)

}

pvalue_search_cpp <- function(h_hat, sigma_jx_t, sorted_max, sqrt_n) {

    .Call(`_forecastdom_pvalue_search_cpp`, h_hat, sigma_jx_t, sorted_max, sqrt_n)
    
}

